---
Name: silverstripe-placeable
After:
  - 'framework/*'
  - 'cms/*'
---
ContentController:
  url_handlers:
    'placement/$ID!/$ACTION!': 'placement'
CMSPageAddController:
  extensions:
    - CMSPageAddControllerPlaceable
LeftAndMain:
  extensions:
    - LeftAndMainPlaceable
  extra_requirements_javascript:
    - placeable/js/Placeable.CMSMain.js
  extra_requirements_css:
    - placeable/css/Placeable.CMSMain.css
SiteTree:
  extensions:
    - SiteTreePlaceable
FieldList:
  extensions:
    - FieldListExtension
